services:

  accounts-service:
    image: especha/projet-accounts:latest
    container_name: accounts-service
    restart: always

  user-service:
    image: especha/projet-user:latest
    container_name: user-service
    restart: always

  frontend:
    image: especha/projet-frontend:latest
    container_name: frontend
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - accounts-service
      - user-service
      - frontend
