version: "3.9"

services:
  user-service:
    image: especha/projet-user:latest
    container_name: user-service
    ports:
      - "9001:9000"

  accounts-service:
    image: especha/projet-accounts:latest
    container_name: accounts-service
    ports:
      - "9002:9000"

  frontend:
    image: especha/projet-frontend:latest
    container_name: frontend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user-service
      - accounts-service
