services:

  accounts-service:
    build: ./services/accounts_service
    container_name: accounts-service
    restart: always

  user-service:
    build: ./services/users_service
    container_name: user-service
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - accounts-service
      - user-service
      - frontend
